
# 2 stage training

# 1st stage -> orientation training
rm -rf checkpoint/FIRST_G8NDB6SN_NPCFNR1-2C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --only_train_normal --logpath FIRST_G8NDB6SN_NPCFNR1-2C1 --epochs 0 --scheduler_mode none --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 6 --flip_normal_mode rightv1_2 --consistency_loss_weight 1.0 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/FIRST_G8NDB6SN_NPCFNR1-3C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --only_train_normal --logpath FIRST_G8NDB6SN_NPCFNR1-3C1 --epochs 0 --scheduler_mode none --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 6 --flip_normal_mode rightv1_3 --consistency_loss_weight 1.0 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/FIRST_G8NDB6SN_NPCFNR2C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --only_train_normal --logpath FIRST_G8NDB6SN_NPCFNR2C1 --epochs 0 --scheduler_mode none --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 6 --flip_normal_mode rightv2 --consistency_loss_weight 1.0 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/FIRST_G8NDB6SN_NPCFNR3C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --only_train_normal --logpath FIRST_G8NDB6SN_NPCFNR3C1 --epochs 0 --scheduler_mode none --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 6 --flip_normal_mode rightv3 --consistency_loss_weight 1.0 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/FIRST_G8NDB6SN_NPCFNR4C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --only_train_normal --logpath FIRST_G8NDB6SN_NPCFNR4C1 --epochs 0 --scheduler_mode none --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 6 --flip_normal_mode rightv4 --consistency_loss_weight 1.0 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/FIRST_G8NDB6SN_NPCFNR5C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --only_train_normal --logpath FIRST_G8NDB6SN_NPCFNR5C1 --epochs 0 --scheduler_mode none --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 6 --flip_normal_mode rightv5 --consistency_loss_weight 1.0 --wandb --wandb_entity CMppProject --wandb_project CMpp


# 2nd stage -> shape training
rm -rf checkpoint/SECOND_G8NDB3_NPCFNR1-2C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --load_ori checkpoint/FIRST_G8NDB6SN_NPCFNR1-2C1/models/last.ckpt --logpath SECOND_G8NDB3_NPCFNR1-2C1 --epochs 0 --scheduler_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 3 --flip_normal_mode rightv1_2 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/SECOND_G8NDB3_NPCFNR1-3C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --load_ori checkpoint/FIRST_G8NDB6SN_NPCFNR1-3C1/models/last.ckpt --logpath SECOND_G8NDB3_NPCFNR1-3C1 --epochs 0 --scheduler_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 3 --flip_normal_mode rightv1_3 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/SECOND_G8NDB3_NPCFNR2C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --load_ori checkpoint/FIRST_G8NDB6SN_NPCFNR2C1/models/last.ckpt --logpath SECOND_G8NDB3_NPCFNR2C1 --epochs 0 --scheduler_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 3 --flip_normal_mode rightv2 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/SECOND_G8NDB3_NPCFNR3C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --load_ori checkpoint/FIRST_G8NDB6SN_NPCFNR3C1/models/last.ckpt --logpath SECOND_G8NDB3_NPCFNR3C1 --epochs 0 --scheduler_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 3 --flip_normal_mode rightv3 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/SECOND_G8NDB3_NPCFNR4C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --load_ori checkpoint/FIRST_G8NDB6SN_NPCFNR4C1/models/last.ckpt --logpath SECOND_G8NDB3_NPCFNR4C1 --epochs 0 --scheduler_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 3 --flip_normal_mode rightv4 --wandb --wandb_entity CMppProject --wandb_project CMpp
rm -rf checkpoint/SECOND_G8NDB3_NPCFNR5C1/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py --scale full --load_ori checkpoint/FIRST_G8NDB6SN_NPCFNR5C1/models/last.ckpt --logpath SECOND_G8NDB3_NPCFNR5C1 --epochs 0 --scheduler_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 3 --flip_normal_mode rightv5 --wandb --wandb_entity CMppProject --wandb_project CMpp


# G8NDB2_F_BV0V0_MH_P0075M0075+N145M145+BD+HNM+NK0+DCOS+AD_NPCFNR1-2_MCM+MNSoft_S1P1_6
main.py --logpath G8NDB2_F_BV0V0_MH_P0075M0075+N145M145+BD+HNM+NK0+DCOS+AD_NPCFNR1-2_MCM+MNSoft_S1P1_6 --backbone vn_unet --double_bacbone vn_unet --n_avn 0 --mlp_mode half --scale full --epochs 0 --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 2 --pos_margin 0.075 --neg_margin 1.45 --pos_offset 0.0 --neg_offset 0.0 --balance_mode double --hard_negative mix --neg_topk 0 --distance_type cossim --anchor_mode default --normal_pred_mode cross --flip_normal_mode rightv1_2 --matching_score_mode CM --matching_norm_mode softmax --p_loss_weight 1.0 --viz_train_epoch 30 --wandb --wandb_entity CMppProject --wandb_project CMpp

# G8NDB3_F_BV0V0_MH_P0075M0075+N145M145+BD+HNM+NK0+DCOS+AD+W10_MCM+MNSoft_S1P1_6
main.py --logpath G8NDB3_F_BV0V0_MH_P0075M0075+N145M145+BD+HNM+NK0+DCOS+AD+W10_MCM+MNSoft_S1P1_6 --backbone vn_unet --double_bacbone vn_unet --n_avn 0 --mlp_mode half --scale full --epochs 0 --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --batch_size 3 --pos_margin 0.075 --neg_margin 1.45 --pos_offset 0.0 --neg_offset 0.0 --balance_mode double --hard_negative mix --neg_topk 0 --distance_type cossim --anchor_mode default --start_hard_neg_epoch 10 --matching_score_mode CM --matching_norm_mode softmax --p_loss_weight 1.0 --viz_train_epoch 30 --wandb --wandb_entity CMppProject --wandb_project CMpp
