:<<end

## TEST
rm -rf checkpoint/TEST_DET_T6_F_AVN_NCD_NPM_NODOCC_OG/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T6_F_AVN_NCD_NPM_NODOCC_OG/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T6_F_AVN_NCD_NPM_NODOCC_OG --scale full --multiplicity 1 --visualize --use_opt_gram --deterministic --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_CM/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/CM_checkpoint/CM_everyday_pa.ckpt --model CM_equiassem --logpath TEST_DET_CM --scale full --multiplicity 1 --deterministic --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_CMbyCMpp/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/CM_checkpoint/CM_everyday_pa.ckpt --model CMpp_equiassem --logpath TEST_DET_CMbyCMpp --scale full --multiplicity 1 --deterministic --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
end


## SMALL TEST
rm -rf checkpoint/DET_T8_S_AVNOON_NCD_NPM_NODOCC_OG_6/ && CUDA_VISIBLE_DEVICES=0 python main.py --model CMpp_equiassem --logpath DET_T8_S_AVNOON_NCD_NPM_NODOCC_OG_6 --scale small --multiplicity 1 --epochs 0 --visualize --only_one_norm --detach_mode --use_opt_gram --deterministic --gpus 0 --n_worker 6 --wandb --wandb_project CMpp &
rm -rf checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6/ && CUDA_VISIBLE_DEVICES=1 python main.py --model CMpp_equiassem --logpath DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6 --scale small --multiplicity 1 --epochs 0 --visualize --detach_mode --use_opt_gram --deterministic --gpus 0 --n_worker 6 --wandb --wandb_project CMpp &
rm -rf checkpoint/DET_T8_S_NCD_NPM_NODOCC_OG_6/ && CUDA_VISIBLE_DEVICES=2 python main.py --model CMpp_equiassem --logpath DET_T8_S_NCD_NPM_NODOCC_OG_6 --scale small --multiplicity 1 --epochs 0 --visualize --n_avn 0 --detach_mode --use_opt_gram --deterministic --gpus 0 --n_worker 6 --wandb --wandb_project CMpp &
rm -rf checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_single_6/ && CUDA_VISIBLE_DEVICES=3 python main.py --model CMpp_equiassem --logpath DET_T8_S_AVN_NCD_NPM_NODOCC_OG_single_6 --scale small --multiplicity 1 --epochs 0 --visualize --scheduler_mode none --detach_mode --use_opt_gram --deterministic --gpus 0 --n_worker 6 --wandb --wandb_project CMpp &


rm -rf checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS/ && CUDA_VISIBLE_DEVICES=4 python main.py --model CMpp_equiassem --logpath DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS --scale small --multiplicity 1 --epochs 0 --visualize --detach_mode --use_opt_gram --deterministic --gpus 0 --delete_Sinkhorn --n_worker 6 --wandb --wandb_project CMpp &
rm -rf checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS_svdNE/ && CUDA_VISIBLE_DEVICES=5 python main.py --model CMpp_equiassem --logpath DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS_svdNE --scale small --multiplicity 1 --epochs 0 --visualize --detach_mode --use_opt_gram --deterministic --gpus 0 --delete_Sinkhorn --svd_no_exp --n_worker 6 --wandb --wandb_project CMpp &
rm -rf checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS/ && CUDA_VISIBLE_DEVICES=6 python main.py --model CMpp_equiassem --logpath DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS --scale small --multiplicity 1 --epochs 0 --visualize --detach_mode --use_opt_gram --deterministic --gpus 0 --matching_score_mode cos --n_worker 6 --wandb --wandb_project CMpp &
rm -rf checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS_DS/ && CUDA_VISIBLE_DEVICES=7 python main.py --model CMpp_equiassem --logpath DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS_DS --scale small --multiplicity 1 --epochs 0 --visualize --detach_mode --use_opt_gram --deterministic --gpus 0 --delete_Sinkhorn --matching_score_mode cos --n_worker 6 --wandb --wandb_project CMpp &

:<<end
rm -rf checkpoint/TEST_DET_T8_S_AVNOON_NCD_NPM_NODOCC_OG_6/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_AVNOON_NCD_NPM_NODOCC_OG_6/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_AVNOON_NCD_NPM_NODOCC_OG_6 --scale small --multiplicity 1 --only_one_norm --use_opt_gram --deterministic --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6 --scale small --multiplicity 1 --use_opt_gram --deterministic --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_T8_S_NCD_NPM_NODOCC_OG_6/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_NCD_NPM_NODOCC_OG_6/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_NCD_NPM_NODOCC_OG_6 --scale small --multiplicity 1 --n_avn 0 --use_opt_gram --deterministic --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_single_6/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_single_6/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_single_6 --scale small --multiplicity 1 --use_opt_gram --deterministic --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test


rm -rf checkpoint/TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS --scale small --multiplicity 1 --use_opt_gram --deterministic --delete_Sinkhorn --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS_svdNE/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS_svdNE/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_DS_svdNE --scale small --multiplicity 1 --use_opt_gram --deterministic --delete_Sinkhorn --svd_no_exp  --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS --scale small --multiplicity 1 --use_opt_gram --deterministic --matching_score_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
rm -rf checkpoint/TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS_DS/ && CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python test.py --load checkpoint/DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS_DS/models/last.ckpt --model CMpp_equiassem --logpath TEST_DET_T8_S_AVN_NCD_NPM_NODOCC_OG_6_MCOS_DS --scale small --multiplicity 1 --use_opt_gram --deterministic --delete_Sinkhorn --matching_score_mode cos --gpus 0 1 2 3 4 5 6 7 --n_worker 6 --move_smaller --wandb --wandb_project CMpp_test
end


